

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cinema_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis-container
    ports:
      - "6379:6379"

  app:

    image: tzunpro10x/cinema-be:v2
    container_name: spring-container
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cinema_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      CLOUD_NAME: dohgdvnuy
      CLOUD_API_KEY: 629845858442262
      CLOUD_API_SECRET: gB6Ld8Agabga0TuyOH1RD9_2BG0

      EMAIL_PASSWORD: bbmskorltuzemmbf
      EMAIL_USERNAME: hien1172004@gmail.com

      JWT_SIGNER_KEY: YvaC4YtaTbPJ9kjAPkauqZ1HlkaqvAkz5jVeaxTGUTpm9YoNVGTU2c98XnWsQo6BLQ9h5n4HcySt0UcvmbBXiL0PpCedzXBxAn3+5FD83H4=

      TMN_CODE: W6HNJ2DM
      TMN_KEY: Q70TTSLZCMHEX6Z13LKF6JR8YX7S9229

volumes:
  mysql_data: